### ISSUE TITLE
If the large name is not found, program should try the parts of it

### ISSUE THREAD

**Issue by asakura42** [druidamix/Opensubtitles-downloader#1]
For example, it doesn't find anything for `Sweet Tooth El.Nino Ciervo - Temporada 2 [HDTV][Cap.203][Castellano].avi` but perfectly finds for `Sweet Tooth - Temporada 2 [HDTV][Cap.203][Castellano].avi`.

**Comment by druidamix** [comment]
Opensubtitles API mainly is based on hash match of the file. Looking using the name is a guess.
Retrying with different parts of the filename is a mess.
